columns:
- nanopore_library_layout
- nanopore_library_protocol
- nanopore_sra_file_path_1
- specimen_processing_id
- description
- illumina_sra_file_path_1
- project_name
- nanopore_sequencing_instrument
- illumina_library_source
- publication_status
- nanopore_library_selection
- ww_surv_target_2_known_present
- ww_surv_target_2_gene
- nanopore_library_name
- fasta_path
- collected_by
- submitting_lab_division
- illumina_sra_file_path_2
- ww_endog_control_1_protocol
- nanopore_library_source
- ww_surv_target_2
- ww_primary_sludge_retention_time
- illumina_library_protocol
- ww_endog_control_2_protocol
- assembly_method
- illumina_library_name
- illumina_library_selection
- publication_title
- illumina_library_layout
- ww_population_source
- submitting_lab_address
- gff_path
- ww_surv_target_2_conc
- purpose_of_ww_sampling
- file_location
- purpose_of_ww_sequencing
- collection_volume
- illumina_sequencing_instrument
- submitting_lab
- authors
- ww_sample_salinity
- ww_total_suspended_solids
- ww_surv_target_2_conc_unit
- nanopore_library_strategy
- mean_coverage
- assembly_protocol
- title
- illumina_library_strategy
